version:                "2"
services:
  datascience-notebook:
      image:            jupyter/datascience-notebook
      volumes:
        - ~/DataScienceTraining:/home/jovyan/work
      ports:
        - 8888:8888
      container_name:   datascience-notebook-container